### ISSUE TITLE
ValueError: offer not found

### ISSUE THREAD

**Issue by alexge233** [tecnovert/basicswap#24]
I've been running BasicSwap in docker for a few days now. Recently I started noticing the below in the logs. Is this expected behaviour? 
See errors below. Let me know if I can help with this (happy to do so).

```
swapclient_1  | 2023-01-09 07:58:23,321 DEBUG : TODO: Expire records from db
swapclient_1  | 2023-01-09 07:59:16,431 DEBUG : Storing revoke request for offer: 0000000063bbc3e2e43808620b2d2feeeb57757b4f10109a2747f721
swapclient_1  | 2023-01-09 07:59:16,432 ERROR : processMsg Offer not found: 0000000063bbc3e2e43808620b2d2feeeb57757b4f10109a2747f721
swapclient_1  | 2023-01-09 07:59:16,432 ERROR : Traceback (most recent call last):
swapclient_1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 5242, in processMsg
swapclient_1  |     self.processOfferRevoke(msg)
swapclient_1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 4056, in processOfferRevoke
swapclient_1  |     raise ValueError('Offer not found: {}'.format(msg_data.offer_msg_id.hex()))
swapclient_1  | ValueError: Offer not found: 0000000063bbc3e2e43808620b2d2feeeb57757b4f10109a2747f721
```

and

```
swapclient_1  | 2023-01-08 23:16:23,506 DEBUG : TODO: Expire records from db
swapclient_1  | 2023-01-08 23:17:07,096 DEBUG : Storing revoke request for offer: 0000000063bb4d6db131a7d24c6262cf45ea990d2f270330fad364a9
swapclient_1  | 2023-01-08 23:17:07,097 ERROR : processMsg Offer not found: 0000000063bb4d6db131a7d24c6262cf45ea990d2f270330fad364a9
swapclient_1  | 2023-01-08 23:17:07,097 ERROR : Traceback (most recent call last):
swapclient_1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 5242, in processMsg
swapclient_1  |     self.processOfferRevoke(msg)
swapclient_1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 4056, in processOfferRevoke
swapclient_1  |     raise ValueError('Offer not found: {}'.format(msg_data.offer_msg_id.hex()))
swapclient_1  | ValueError: Offer not found: 0000000063bb4d6db131a7d24c6262cf45ea990d2f270330fad364a9
swapclient_1  | 
```

```
apclient_1  | 2023-01-08 22:51:41,433 DEBUG : Storing revoke request for offer: 0000000063bb472d3c3415b5c85329abfa9b027421739a9ea658055e
swapclient_1  | 2023-01-08 22:51:41,434 ERROR : processMsg Offer not found: 0000000063bb472d3c3415b5c85329abfa9b027421739a9ea658055e
swapclient_1  | 2023-01-08 22:51:41,434 ERROR : Traceback (most recent call last):
swapclient_1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 5242, in processMsg
swapclient_1  |     self.processOfferRevoke(msg)
swapclient_1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 4056, in processOfferRevoke
swapclient_1  |     raise ValueError('Offer not found: {}'.format(msg_data.offer_msg_id.hex()))
swapclient_1  | ValueError: Offer not found: 0000000063bb472d3c3415b5c85329abfa9b027421739a9ea658055e
swapclient_1  | 
swapclient_1  | 2023-01-08 22:51:47,459 DEBUG : Storing revoke request for offer: 0000000063bb472d3c3415b5c85329abfa9b027421739a9ea658055e
swapclient_1  | 2023-01-08 22:51:47,460 ERROR : processMsg Offer not found: 0000000063bb472d3c3415b5c85329abfa9b027421739a9ea658055e
swapclient_1  | 2023-01-08 22:51:47,460 ERROR : Traceback (most recent call last):
swapclient_1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 5242, in processMsg
swapclient_1  |     self.processOfferRevoke(msg)
swapclient_1  |   File "/usr/local/lib/python3.10/dist-packages/basicswap/basicswap.py", line 4056, in processOfferRevoke
swapclient_1  |     raise ValueError('Offer not found: {}'.format(msg_data.offer_msg_id.hex()))
swapclient_1  | ValueError: Offer not found: 0000000063bb472d3c3415b5c85329abfa9b027421739a9ea658055e
```

**Comment by seasharpfoss** [comment]
@tecnovert It looks like this issue can be closed based on https://github.com/tecnovert/basicswap/commit/c13606ab54cc3da0a3535cb54e307b4e457ac1c6

Is that correct?

**Comment by tecnovert** [comment]
> @tecnovert It looks like this issue can be closed based on [c13606a](https://github.com/tecnovert/basicswap/commit/c13606ab54cc3da0a3535cb54e307b4e457ac1c6)
> 
> Is that correct?

Correct thanks, versions after that commit should only show a message for unknown revoked offers if debug mode is active.
